export enum DisplayCategory {
  STATS = "STATS",
  MAGIE = "MAGIE",
  ARCANES = "ARCANES",
  ARCANES_PRIMES = "ARCANES_PRIMES",
  BONUS = "BONUS",
  SOLDATS = "SOLDATS",
  PACIFICATEURS = "PACIFICATEURS",
  PAROLIERS = "PAROLIERS",
  TECHNOMANCIE = "TECHNOMANCIE",
  SOUTIENS = "SOUTIENS",
}
